services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: applications-api-php
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.27-alpine
    container_name: applications-api-nginx
    depends_on:
      php:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./:/app:ro
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: applications-api-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pg-data:
  php-vendor:
